

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 
 terms will be:
        1 , 2 , 3  , 5  , 8  , 13  , 21  , 34  , 55  , 89 ......
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include<stdio.h>
#include<conio.h>

int main()
{
    int a=1,b=2,c,sum=0;

    printf(" %d , %d ",a,b);
    // for(int i=0 ; i<10 ; i++)
    do
    {
        c=a+b;
        a=b;
        b=c;
        if(c<4000000)
        {
         printf(", %d  ",c);
         
         if(c%2==0)
         {
            sum+=c;

         }
         
        }

    }while(c<4000000);
    printf("\nSum is = %d",sum+2);

    return 0;
}